### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by Naheel-Azawy** [tranvinhduc/abe#1]
I've gone over the paper and I am interested in your work!
Can you please provide some documentation about the usage of it? I can see from the `runtest.sh` that it takes a (test) file and the parameters are fed from the stdin. But what are the tests and parameter exactly? How are they structured? And what is the meaning of the output of the program?

One more unrelated question. Why `runtest.sh` is using `zsh`?.. Just use `sh` I guess.

**Comment by birdssu** [comment]
I want to know the code of which paper. You can send me the title of the paper, so that I can find out which code you are talking about

**Comment by Naheel-Azawy** [comment]
@birdssu The README clearly states that this is an implementation of a paper... Here's a link to save you searching time https://www.sciencedirect.com/science/article/abs/pii/S014036641930324X

**Comment by tranvinhduc** [comment]
> I've gone over the paper and I am interested in your work!
> Can you please provide some documentation about the usage of it? I can see from the `runtest.sh` that it takes a (test) file and the parameters are fed from the stdin. But what are the tests and parameter exactly? How are they structured? And what is the meaning of the output of the program?
> 
> One more unrelated question. Why `runtest.sh` is using `zsh`?.. Just use `sh` I guess.

**Comment by tranvinhduc** [comment]
Dear @Naheel-Azawy  
- For parameter,  I copied from https://crypto.stanford.edu/pbc/  . For the test, you can use the pairing a.param (type 1) or type f.param (type 3).
- The data tests are randomly generated.

**Comment by birdssu** [comment]
You can try to use VC + + 6.0 and visual studio to rebuild the code. I've rewritten this code, but I can't run it correctly.

**Comment by birdssu** [comment]
This is my main function:
`#include <stdio.h>
#include "abe.h"
#include <pbc.h>
#include "bintree.h"
#include "readfile.h"
#include "precomp.h"
#include <pbc_lib.h>


#define NUMTEST 1

void main()
{
	clock_t start,end;
	int i = 0;
//   int argc=2;

    DNF beta;
    Set subset;
/*
    if (argc < 1)
    {
        perror("Usage: abe datafile");
        exit(-1);
    }
 */   
	readFiles("21.txt", &subset, &beta);
    printf ("Data file: %s\n", "21.txt");

    
    start = clock();
    
    Setup();
    
    end = clock();

	cout<<"Setup time:"<<end-start<<"ms"<<endl;
	cout<<"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"<<endl;
    
    //printf ("Setup: %fs\n", end-start);   
    Secret_key_user du;    
    start = clock();
    Extract (&du, &subset);
    end = clock();
	cout<<"Extract time:"<<end-start<<"ms"<<endl;
	cout<<"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"<<endl;
  
    element_t M1;
    element_init_GT(M1, pairing);
    element_random(M1);
    cout<<"密文为："<<endl;
	element_printf("%B\n", M1);

    Cipher_text ct;
    element_t M2;

    double everage = 0;
    for (i=0; i < NUMTEST; i++) {
        start = clock();
        EncryptLSSS(&ct, M1, &beta);
        end = clock();
        everage += (end-start);
    }
  // printf ("&%4f ms ", everage*1000.0/NUMTEST);
  // printf ("EncryptLSSS: %f s\n", everage/NUMTEST);
	cout<<"EncryptLSSS time:"<<everage/NUMTEST<<"ms"<<endl;
	cout<<"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"<<endl;
    
    everage = 0;
    for(i = 0; i < NUMTEST; i++){
        start = clock();
        DecryptLSSS(M2, &ct, &beta, &du);
        end = clock();
        everage += (end-start);
    }
	cout<<"DecryptLSSS time:"<<everage/NUMTEST<<"ms"<<endl;
	cout<<"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"<<endl;
 
    if (!element_cmp(M1, M2))
        printf ("LSSS Decrypt: OK!\n");
    else printf ("LSSS Decrypt: Error!\n");

	cout<<"LSSS解密数据为："<<endl;
	element_printf("%B\n", M2);

    free_cipher_text(&ct);

    everage = 0;
    
    for (i = 0; i < NUMTEST; i++)
    {
        start = clock();
        Encrypt(&ct, M1, &beta);
        end = clock();
        everage += (end-start);
    }
	cout<<"Encrypt time:"<<end-start<<"ms"<<endl;
	cout<<"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"<<endl;
    
    everage = 0;

    for (i = 0; i < NUMTEST; i++) {
        start = clock();
        Decrypt(M2, &ct, &beta, &du);
        end = clock();
        everage += (end - start);
    }
	cout<<"Decrypt time:"<<end-start<<"ms"<<endl;
	cout<<"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"<<endl;
  
    if (!element_cmp(M1, M2))
        printf ("Decrypt: OK!\n");
    else printf ("Decrypt: Error!\n");

	cout<<"解密数据为："<<endl;
	element_printf("%B\n", M2);

    free_cipher_text(&ct);

    
    free_secret_key_user(&du);

    element_clear(M1);
    element_clear(M2);
    element_clear(MSK);
    free_global_parameters(&param);
    pairing_clear(pairing);
}
`

**Comment by birdssu** [comment]
I think this code should give you some inspiration.

**Comment by Naheel-Azawy** [comment]
@birdssu  Thanks but I don't use Windows... I did compile it btw and it did run correctly. No idea how to do it in Windows probably you need something like `msys2` I guess. But in Linux, while on the project directory,
```
cd src
make
mv abe ../
cd ..
sh runtest.sh
```
